name: Docker Image CI
on:
push:
  branches: [ "master" ]
pull_request:
  branches: [ "master" ]

jobs:     
      
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v
        with:
          version: v..
      - name: Login to DockerHub
        uses: docker/login-action@v
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v
        with:
          push: true
          tags: milankoelen/jsonAnalyzer:prod
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}